// Methodology + disclaimer page. Must make the heuristic nature of the
// classifier extremely clear — this is not legal advice.

export function About() {
  return (
    <div className="prose prose-slate max-w-none">
      <h1 className="text-2xl font-semibold text-slate-900">About Nazar Watch</h1>

      <p className="text-sm text-slate-700">
        Nazar Watch is an open-source project that tracks how Meta, OpenAI,
        Anthropic, Google, Microsoft, and more revise their privacy policies, terms,
        and related disclosures over time, with a focus on language relevant
        to AI data use.
      </p>

      <p className="text-sm text-slate-700">
        The name is a nod to the <em>nazar</em> — the concentric-eye amulet
        common across the Mediterranean and Middle East, traditionally hung
        to watch for and ward off harm. Fitting, for a site whose job is to 
        keep an eye on the companies quietly rewriting the rules for what they 
        can do with your data.
      </p>

      <h2 className="mt-6 text-lg font-semibold text-slate-900">
        Not legal advice
      </h2>
      <p className="text-sm text-slate-700">
        Nothing on this site is legal advice. The classifications are
        generated by rule-based keyword matching and will produce both
        false positives and false negatives. Every change links to its
        original source; read the original before drawing conclusions.
        There are also AI summaries available, but these are unreviewed and 
        should be verified independently.
      </p>

      <h2 className="mt-6 text-lg font-semibold text-slate-900">
        Data sources
      </h2>
      <ul className="list-disc pl-6 text-sm text-slate-700">
        <li>
          <strong>Privacy policies and terms</strong> — direct HTTPS fetches
          of each company's canonical policy URLs, polite 2-second-per-host
          cadence, robots.txt respected. Historical snapshots seeded from
          the Internet Archive's Wayback Machine CDX API over the last 24
          months.
        </li>
        <li>
          <strong>SEC filings</strong> — EDGAR submissions feed, 10-K and
          10-Q filings only, with AI-keyword paragraph extraction for
          storage bounds.
        </li>
        <li>
          <strong>Regulatory</strong> — FTC RSS, EU Commission press
          corner, California AG news, filtered to AI and privacy keywords.
        </li>
        <li>
          <strong>News</strong> — GDELT 2.0 DOC API, metadata only (URL,
          title, source domain, tone). Article text is never stored.
        </li>
      </ul>

      <h2 className="mt-6 text-lg font-semibold text-slate-900">
        How a change is detected
      </h2>
      <p className="text-sm text-slate-700">
        Each day the scraper writes a plain-text snapshot of every tracked
        policy. A content hash suppresses duplicates. The analysis pipeline
        splits each snapshot into paragraphs and compares consecutive dates
        using Python's <code>difflib.SequenceMatcher</code>. Replaced
        paragraphs are greedily paired by similarity; paragraphs below a
        0.5 similarity threshold are recorded as separate added and
        removed items rather than a modification.
      </p>

      <h2 className="mt-6 text-lg font-semibold text-slate-900">
        How tags are assigned
      </h2>
      <p className="text-sm text-slate-700">
        A YAML rule file defines regex patterns for each tag
        (ai-training-expansion, data-retention-change, biometric-facial,
        etc.). Ambiguous keywords like "training" also require a nearby
        qualifier such as "AI" or "model" to fire. Only added and modified
        text is scanned — the tracker surfaces new language, not deletions.
      </p>

      <h2 className="mt-6 text-lg font-semibold text-slate-900">
        How significance is scored
      </h2>
      <ul className="list-disc pl-6 text-sm text-slate-700">
        <li>+3 if the change has real content (not navigation or boilerplate)</li>
        <li>+2 for each matched change-type tag</li>
        <li>+2 if the change only adds paragraphs (no modifications)</li>
        <li>+1 if tracked keywords appear in a heading-like paragraph</li>
        <li>Total capped at 10. Timeline threshold: 4.</li>
      </ul>

      <h2 className="mt-6 text-lg font-semibold text-slate-900">
        Limitations
      </h2>
      <p className="text-sm text-slate-700">
        Some policy URLs are protected by bot walls and may capture junk
        HTML. News and regulatory listings are heuristic HTML scrapes and
        can break when source sites redesign. The classifier is keyword
        matching, not natural language understanding — synonyms and
        paraphrases will be missed. Contributions to the rule dictionary
        are welcome via pull request.
      </p>
    </div>
  );
}
